### ISSUE TITLE
SHIT'S BROKE

### ISSUE THREAD

**Issue by IAMAVelociraptorAMA** [mutoid/ccbot#22]
LET US QUOTE WITH @FUNCTIONALITY

**Comment by citz** [comment]
I made this ticket too but better

**Comment by mutoid** [comment]
Duplicate of earlier issue #25

**Comment by citz** [comment]
my ticket was better

**Comment by citz** [comment]
lol muty you closed both tickets

I'm on to you, you're just trying to get out of work!
